### ISSUE TITLE
Using breakout with scrollbars causes overflow

### ISSUE THREAD

**Issue by Muffinman** [LucidNinja/tailwind-container-break-out#2]
Depending on the platform (e.g. Linux, Windows), `100vw` can include the width of the scrollbar. This can lead to situations where horizontal scrollbars are sometimes created.

To get around this, perhaps a scrollbar width should be calculated and taken into account?

e.g.

```css
:root {
  --scrollbar-width: calc(100vw - (100vw - 100%));
}
```

https://stackoverflow.com/questions/33606565/is-it-possible-to-calculate-the-viewport-width-vw-without-scrollbar
